# Generated by Django 5.1.3 on 2024-12-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_author_name_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='location',
            field=models.CharField(default='Default location', max_length=255),
        ),
    ]
